---
- name: Sanoid config directory
  ansible.builtin.file:
    path: /etc/sanoid
    state: directory
    mode: "0755"

- name: Sanoid config
  ansible.builtin.template:
    src: sanoid.conf.j2
    dest: /etc/sanoid/sanoid.conf
    mode: "0644"
  notify: Restart sanoid

- name: Enable sanoid timer
  ansible.builtin.systemd:
    name: sanoid.timer
    enabled: true
    state: started
